apiVersion: v1
kind: Service
metadata:
  name: yarp-proxy
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 8443
      targetPort: 8443
  selector:
    app: yarp-proxy
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: yarp-proxy
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: yarp-proxy
  namespace: default
rules:
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yarp-proxy
  namespace: default
subjects:
- kind: ServiceAccount
  name: yarp-proxy
  namespace: default
roleRef:
  kind: Role
  name: yarp-proxy
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarp-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yarp-proxy
  template:
    metadata:
      labels:
        app: yarp-proxy
    spec:
      containers:
      - name: yarp-proxy
        image: yixiansootestappacr.azurecr.io/yarp-proxy:latest
        ports:
        - containerPort: 8080
        - containerPort: 8443
        volumeMounts:
        - name: tls
          mountPath: "/app/certs"
          readOnly: true
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080;https://+:8443"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: "/app/certs/tls.crt"
        - name: ASPNETCORE_Kestrel__Certificates__Default__KeyPath
          value: "/app/certs/tls.key"
      volumes:
      - name: tls
        secret:
          secretName: yarp-tls